// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface ItemsSchema {
  categories: Category[]
  classes: ChampionClass[] | null
  description: null | string
  from: number[] | null
  gold: Gold | null
  icon: null | string
  iconOverlay: boolean | null
  id: number | null
  inStore: boolean
  into: number[] | null
  maps: number[] | null
  maxStacks: number
  mythic: boolean | null
  name: null | string
  nicknames: string[] | null
  requiredChampion: RequiredChampion | null
  simpleDescription: null | string
  stats: { [key: string]: number } | null
  tier: number | null
  visible: boolean
}

export enum Category {
  All = 'All',
  AbilityHaste = 'AbilityHaste',
  Active = 'Active',
  Armor = 'Armor',
  ArmorPenetration = 'ArmorPenetration',
  AttackSpeed = 'AttackSpeed',
  Aura = 'Aura',
  Boots = 'Boots',
  Consumable = 'Consumable',
  CooldownReduction = 'CooldownReduction',
  CriticalStrike = 'CriticalStrike',
  AttackDamage = 'Damage',
  GoldPer = 'GoldPer',
  Health = 'Health',
  HealthRegen = 'HealthRegen',
  Jungle = 'Jungle',
  Lane = 'Lane',
  LifeSteal = 'LifeSteal',
  MagicPenetration = 'MagicPenetration',
  Mana = 'Mana',
  ManaRegen = 'ManaRegen',
  NonbootsMovement = 'NonbootsMovement',
  OnHit = 'OnHit',
  Slow = 'Slow',
  MagicResistance = 'SpellBlock',
  AbilityPower = 'SpellDamage',
  SpellVamp = 'SpellVamp',
  Stealth = 'Stealth',
  Tenacity = 'Tenacity',
  Trinket = 'Trinket',
  Vision = 'Vision',
}

export enum ChampionClass {
  Assassin = 'ASSASSIN',
  Fighter = 'FIGHTER',
  Mage = 'MAGE',
  Marksman = 'MARKSMAN',
  Support = 'SUPPORT',
  Tank = 'TANK',
  None = 'None',
}

export interface Gold {
  base: number
  purchasable: boolean
  total: number
  sell: number
}

export enum RequiredChampion {
  Empty = '',
  FiddleSticks = 'FiddleSticks',
  Gangplank = 'Gangplank',
  Kalista = 'Kalista',
}
